name: flutter_application_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_analytics: ^11.0.1
  firebase_core: ^3.1.0
  google_fonts: ^6.2.1
  flutter:
    sdk: flutter
  flutter_data_table: ^1.1.2
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  syncfusion_flutter_charts: ^26.1.38
  syncfusion_flutter_datagrid: ^26.1.38

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets\image.png
    - assets2\image.png
    - assets3\image.png 
    - assets4\image.png 
    - assets5\image.png 
    - assets6\image.png 
    - assets7\image.png 
    - assets8\image.png 
    - assets9\image.png 
    - assets10\image.png 
    - assets11\image.png 
    - assets12\image.png 
    - assets13\image.png 
    - assets14\image.png
    - assets15\image.png
    - assets16\image.png
    - assets17\image.png
    - assets18\image.png
    - assets19\image.png 
    - assets20\image.png
    - assets21\image.png  

fonts:
  - family: MaterialIcons
    fonts:
      - asset: fonts/MaterialIcons-Regular.ttf # Default path to MaterialIcons font file

  - family: CupertinoIcons
    fonts:
      - asset: fonts/cupertino-icons.ttf

web:
  plugin:
    plugins:
      firebase_core_web:
        path: packages/firebase_core_web
      firebase_analytics_web:
        path: packages/firebase_analytics_web
