name: flutter_application_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  echart_flutter: ^0.1.0+2
  flutter:
    sdk: flutter
  flutter_data_table: ^1.1.2
  provider: ^6.1.2
  syncfusion_flutter_charts: ^26.1.38
  syncfusion_flutter_datagrid: ^26.1.38

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets\image.png
    - assets2\image.png
